services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: adm1n
      POSTGRES_PASSWORD: adm1n
      POSTGRES_DB: aurelius
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adm1n -d aurelius"]
      interval: 3s
      timeout: 3s
      retries: 5

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
  
  lb-get:
    build: ./load-balancer
    container_name: lb-get
    environment:
      - TARGETS=http://backend-get-1:8080,http://backend-get-2:8080
  
  lb-post:
    build: ./load-balancer
    container_name: lb-post
    environment:
      - TARGETS=http://backend-post-1:8080,http://backend-post-2:8080

  lb-put:
    build: ./load-balancer
    container_name: lb-put
    environment:
      - TARGETS=http://backend-put-1:8080,http://backend-put-2:8080

  backend-get-1: &backend-base
    build: ./backend
    container_name: backend-get-1
    environment: &backend-env
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: adm1n
      DB_PASSWORD: adm1n
      DB_NAME: aurelius
      ROLE: get
      DEBUG_WORKER_ID: 1
    depends_on:
      db:
        condition: service_healthy

  backend-get-2:
    <<: *backend-base
    container_name: backend-get-2
    environment:
      <<: *backend-env
      ROLE: get
      DEBUG_WORKER_ID: 2

  backend-post-1:
    <<: *backend-base
    container_name: backend-post-1
    environment:
      <<: *backend-env
      ROLE: post
      DEBUG_WORKER_ID: 3

  backend-post-2:
    <<: *backend-base
    container_name: backend-post-2
    environment:
      <<: *backend-env
      ROLE: post
      DEBUG_WORKER_ID: 4

  backend-put-1:
    <<: *backend-base
    container_name: backend-put-1
    environment:
      <<: *backend-env
      ROLE: put
      DEBUG_WORKER_ID: 5

  backend-put-2:
    <<: *backend-base
    container_name: backend-put-2
    environment:
      <<: *backend-env
      ROLE: put
      DEBUG_WORKER_ID: 6